name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag doron-bot:$(date +%s)

    - name: Tag the image
      run: docker tag doron-bot:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/doron-bot:latest

    - name: Push the image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/doron-bot:latest
